version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_berneck
    restart: always
    environment:
      POSTGRES_USER: usr_berneck
      POSTGRES_PASSWORD: usr_berneck
      POSTGRES_DB: db_berneck
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: